import type { Story } from '../types';
import { countWords } from '../lib/words';

const raw: Omit<Story, 'wordCount' | 'language' | 'source'>[] = [
  {
    id: 'en-mochi-at-midnight',
    tier: 1,
    title: 'Mochi at Midnight',
    cover: 'cat-night',
    accent: '#7a5a3a',
    paragraphs: [
      'Everyone in the house was asleep. The lights were off, and the curtains were drawn. Mochi the kitten opened her bright green eyes. It was time for her secret midnight adventure.',
      'She jumped softly from the warm bed where Lily was sleeping. Her paws made no sound on the wooden floor. Down the dark hallway she went, past the open bedroom doors. The moon poured through the kitchen window in a wide silver river.',
      'In the kitchen, Mochi found a paper bag on the floor. Paper bags were her very favorite thing in the world. She sniffed at it, then leaped inside with one quick pounce. Crinkle, crinkle, crinkle. The bag wiggled and shook. Then her small black nose poked out, full of pride.',
      'Outside, an owl called from somewhere in the trees. Hoo. Hoo. Mochi tipped her head and listened. She wanted to see the owl. She padded over to the back door and peeked through the small cat flap.',
      'The garden was full of mysterious shadows. A bush moved gently in the wind. A small bug zipped past. Mochi’s tail twitched with excitement. But it was a little cold outside, and she was not quite that brave tonight.',
      'She turned and walked back to the kitchen. She ate three small pieces of dry food from her bowl. Then she climbed the stairs slowly, paw by careful paw.',
      'Up in the bedroom, Lily was still fast asleep. Mochi curled up on the pillow next to her, like a soft, warm cloud. She closed her green eyes. Her midnight adventure was over for tonight.',
    ],
    comprehension: [
      {
        q: 'What did Mochi find in the kitchen?',
        options: ['A bowl of milk', 'A paper bag', 'A toy mouse'],
        correctIndex: 1,
      },
      {
        q: 'Why did Mochi not go outside?',
        options: [
          'The cat flap was locked',
          'It was cold and she was not that brave',
          'Lily called her back',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-the-paper-boat',
    tier: 2,
    title: 'The Paper Boat',
    cover: 'paper-boat',
    accent: '#3a6a9a',
    paragraphs: [
      'After the rain finally stopped, Theo went outside with his new yellow boots and a small folded paper boat. The boat had a tall blue sail, drawn carefully in marker by his grandmother. The street was full of puddles, but Theo had a much bigger plan in mind.',
      'He walked down the lane to the small stream that ran behind the old stone wall. The water moved gently after the rain, carrying leaves and tiny twigs along like little passengers. Theo crouched at the edge of the bank and held his paper boat carefully with both hands.',
      '“Goodbye, little boat,” he whispered. “Have a very good trip.”',
      'He set it on the water. The boat wobbled. For one scary moment, it tilted to the side, and Theo nearly grabbed it back. Then it found its balance, and the stream carried it forward, slow and brave.',
      'Theo walked along the bank, watching his boat. It floated past a brown rock that looked exactly like a sleeping turtle. It spun once around a soft patch of green moss. A small frog watched from the grass with shiny black eyes, but the boat sailed on, with its tall blue sail held high.',
      'A little further along, the stream split into two. The boat hesitated for a moment, bobbing in the middle. Then it chose the path on the right, the one that led under a low wooden bridge. Theo ran to keep up, his yellow boots splashing in the puddles.',
      'Past the bridge, the stream opened into a wider, sunny pool. Lily pads floated on the water like flat green plates. A dragonfly with bright blue wings hovered low to inspect the new visitor. The paper boat sailed bravely across the pool, just like a real ship in a real ocean.',
      'At the far side, the stream slipped under a tangle of bushes and was gone. Theo could not follow it any further. He stood with his hands in his pockets, watching the last little flash of paper disappear into the green leaves.',
      'His grandmother had told him that paper boats only sail once. They go off on their own adventure, and they do not come back. Theo did not feel sad. He felt happy, and a little proud. Somewhere in the woods, his small blue sail was still moving forward, going wherever the water wanted to go.',
    ],
    comprehension: [
      {
        q: 'Who drew the sail on the boat?',
        options: ['His mom', 'His grandmother', 'His teacher'],
        correctIndex: 1,
      },
      {
        q: 'How did Theo feel at the end of the story?',
        options: [
          'Sad and lonely',
          'Happy and a little proud',
          'Tired and grumpy',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-granddads-telescope',
    tier: 2,
    title: 'Granddad’s Telescope',
    cover: 'telescope',
    accent: '#3d3a6e',
    paragraphs: [
      'It was Maya’s favorite night of the whole year. Every July, she stayed at Granddad’s little house on the hill, and they always did the same wonderful thing together.',
      'After dinner, Granddad opened the cupboard under the stairs and took out a long brass telescope. It was old, and a little scratched, but it shone in the light of the kitchen lamp. Granddad polished the round eyepiece carefully with his soft blue cloth.',
      '“Are the clouds still hiding the sky?” Maya asked, peeking out the window.',
      '“Not anymore,” said Granddad, with a small wink. “Come outside and see.”',
      'They walked out into the cool evening air. The grass was already damp with dew. Maya wore her grandmother’s old wool sweater, which was warm and smelled a little like cinnamon. Granddad set up the telescope on its three sturdy wooden legs and pointed it at the dark sky.',
      'The first thing they looked at was the moon. Through the telescope, the moon was not just a flat white circle anymore. It was a round, bumpy world, full of mountains and craters. Maya could see the long shadow of a cliff. She could see the small dark seas that the moon was famous for. She held her breath.',
      '“It looks like a place I could walk on,” she whispered.',
      '“One day, perhaps,” said Granddad.',
      'Next, he turned the telescope toward a small cluster of bright stars. They were called the Seven Sisters, he said. To Maya, they looked like a tiny scattering of jewels on a blue cloth.',
      'After that, they found a planet, low and orange near the horizon. Granddad said it was called Mars. Through the telescope, it was a fuzzy little dot, not as clear as the moon. But Maya did not mind. Mars was a whole world too, just very, very far away.',
      'When Maya’s eyes started to feel sleepy, Granddad let her look at one last thing. He turned the telescope toward a faint, pale smudge between two stars. He called it a galaxy. He said it was so far away that the light reaching their eyes had been traveling for over two million years.',
      'Maya did not say anything for a long time. She thought about light, and distance, and her own small place in everything.',
      'Granddad rested his big warm hand gently on her shoulder. Maya leaned against him. Above them, the whole sky kept turning, just as it had always done, and just as it always would.',
    ],
    comprehension: [
      {
        q: 'What special thing did Granddad take from the cupboard?',
        options: [
          'A book of star maps',
          'A long brass telescope',
          'A pair of binoculars',
        ],
        correctIndex: 1,
      },
      {
        q: 'How long has the light from the galaxy been traveling?',
        options: [
          'Just a few minutes',
          'About a thousand years',
          'Over two million years',
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: 'en-the-lighthouse-apprentice',
    tier: 3,
    title: 'The Lighthouse Apprentice',
    cover: 'lighthouse',
    accent: '#a85d2e',
    paragraphs: [
      'Sam visited the old lighthouse every summer. The keeper, Mr. Brennan, had bushy white eyebrows, kind brown eyes, and a laugh that sounded a little like a creaking door. He had been keeping the great light shining for thirty-six years.',
      'This summer, Sam was finally tall enough to climb to the lamp room by himself. He had practiced the long spiral staircase for three days, counting each step out loud as he went. There were one hundred and sixty-eight of them in all.',
      'On Sam’s fourth day, the weather turned. The sky filled with heavy grey clouds, and the sea below began to throw white spray against the rocky cliffs. By the afternoon, the wind was rattling the windows of the keeper’s small stone cottage.',
      'Mr. Brennan came out of the kitchen holding a tin mug of tea. “Tonight will be a busy night,” he said quietly. “The lamp must shine extra bright. There are still fishing boats out there.”',
      'Sam looked at him with serious eyes. “Can I help?”',
      'Mr. Brennan smiled. “Yes, you can. Tonight, you will be my apprentice.”',
      'They climbed the long staircase together, slowly, because the storm was making the lighthouse feel a little like a tree in the wind. At the very top, the lamp room was warm and full of soft golden light. The great lamp itself was a beautiful machine, made all of polished brass and curved glass. It rotated steadily, sending a long bright beam out into the darkening sky.',
      'Sam’s job was to polish each of the glass panels with a soft white cloth. He worked carefully, one panel at a time, making sure to leave no streaks behind. Mr. Brennan checked each gear and added a small drop of oil to the parts that needed it. Outside, the wind howled and the rain hammered, but inside the lamp room, everything stayed calm and steady.',
      'When night fell properly, Sam pressed his nose against the cold glass. Down below, the black sea was wild with crashing waves. Far out, near the edge of the storm, he saw a tiny moving light. It was a boat.',
      '“Look!” Sam said. “Will they be alright?”',
      'Mr. Brennan stood beside him and watched. The little light tilted back and forth in the waves, but it did not go out. It moved slowly, slowly, toward their beam of light.',
      '“They’re heading for the harbor,” Mr. Brennan said. “Our lamp is telling them where the safe path is.”',
      'Sam felt very small, and very important, both at the same time. He stood there for a long while, watching the small light grow a tiny bit bigger. The wind kept howling. The waves kept crashing. But the lamp kept turning, slow and bright and steady, just as it had every single night for over a hundred years.',
      'When the storm finally passed, near midnight, Sam was almost asleep on the small wooden stool by the door. Mr. Brennan picked him up gently and carried him down the spiral stairs, one careful step at a time. Outside, the sky was clearing. Somewhere out at sea, a small fishing boat was finally reaching the safety of the harbor.',
    ],
    comprehension: [
      {
        q: 'How many steps lead up to the lamp room?',
        options: ['Thirty-six', 'One hundred', 'One hundred and sixty-eight'],
        correctIndex: 2,
      },
      {
        q: 'What was Sam’s job that night?',
        options: [
          'To polish each glass panel',
          'To light the lamp with a match',
          'To watch from the kitchen',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'en-the-fox-and-the-mitten',
    tier: 1,
    title: 'The Fox and the Mitten',
    cover: 'fox-snow',
    accent: '#b86a4d',
    paragraphs: [
      'It was snowing softly in the forest. A small red fox named Pim was looking for something to eat. Her paws made little prints in the fresh white snow.',
      'Under a tall pine tree, Pim found something strange. It was warm, and woolly, and bright blue. It was a child’s mitten, with a little white star sewn on the front.',
      'Pim sniffed it carefully. It smelled like a person, and a small dog, and a little bit like cookies. It must belong to someone, she thought.',
      'Pim picked up the mitten gently with her teeth. She trotted through the snowy trees, past the frozen pond, and out to the edge of the forest. There, she could see a small wooden house with smoke curling from the chimney.',
      'A little girl in a bright red coat was building a snowman in the yard. She had one blue mitten on her left hand. Her right hand was bare and pink from the cold.',
      'Pim stopped at the edge of the yard. She was a little shy. She placed the mitten carefully in the snow, then took three quiet steps back.',
      'The little girl saw her and gasped. She walked over slowly, picked up the mitten, and smiled. Then she put it back on her cold pink hand.',
      '“Thank you,” she whispered.',
      'Pim wagged her bushy tail just once. Then she turned and ran back into the snowy forest, her job done.',
    ],
    comprehension: [
      {
        q: 'What was special about the mitten Pim found?',
        options: [
          'It was red with a moon on it',
          'It was blue with a white star',
          'It was striped',
        ],
        correctIndex: 1,
      },
      {
        q: 'How did Pim give the mitten back?',
        options: [
          'She dropped it at the front door',
          'She placed it in the snow and stepped back',
          'She handed it to the little girl',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-the-garden-snail',
    tier: 1,
    title: 'The Garden Snail',
    cover: 'snail-garden',
    accent: '#5f8a4d',
    paragraphs: [
      'Lila loved her grandmother’s garden. There were strawberries, red tomatoes, and tall yellow sunflowers that turned their faces to follow the sun.',
      'One sunny morning, Lila noticed a tiny visitor on the leaf of her favorite strawberry plant. It was a small brown snail, with a swirly shell. He was eating a tiny bite of leaf.',
      '“Hello,” said Lila softly. “Are you helping in the garden?”',
      'The snail did not answer, of course. But he waved his little eye-stalks slowly.',
      'Grandma came out with a big watering can. “Oh,” she laughed, “you’ve met Mr. Pickles.”',
      '“Mr. Pickles?” Lila said.',
      '“That’s what I call him. He has lived in this garden for a long, long time. He eats a few leaves, but he is also a tiny gardener. He helps the plants grow.”',
      'Lila looked at the snail with new respect. He moved so slowly. He left a shiny silver trail behind him.',
      'That afternoon, Lila brought him a fresh piece of lettuce from the kitchen. She placed it gently near the strawberry plant. By the next morning, the lettuce was almost gone, and Mr. Pickles was sitting happily on top of it.',
      'Lila smiled. She and Mr. Pickles were going to be very good friends, she decided. Even if they would walk through the garden at very different speeds.',
    ],
    comprehension: [
      {
        q: 'What is the snail’s name?',
        options: ['Mr. Sprinkles', 'Mr. Pickles', 'Mr. Whiskers'],
        correctIndex: 1,
      },
      {
        q: 'What did Lila bring for the snail?',
        options: ['A strawberry', 'A piece of lettuce', 'Some water'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-the-drawing-that-came-alive',
    tier: 2,
    title: 'The Drawing That Came Alive',
    cover: 'drawing',
    accent: '#7a4a9a',
    paragraphs: [
      'It was a rainy Saturday, and Ben had nothing to do. He sat at the kitchen table with his old wooden pencil and a fresh sheet of white paper. Outside, the rain pattered against the window like a sleepy drum.',
      'Ben decided to draw something special. He drew a small round island, with one tall palm tree on it. He drew a tiny boat with a yellow sail. He drew a friendly little octopus waving from the blue water.',
      'When he was finished, he put down his pencil and stretched. Then something very strange happened.',
      'The little boat in his drawing began to move. It bobbed gently, as if on real waves. The palm tree swayed. And the octopus winked at him with one round eye.',
      'Ben gasped. He held very still, watching.',
      'The boat sailed slowly across the paper, then off the edge, and onto the table. It glided across the kitchen, leaving a tiny wet trail. The octopus flopped after it, waving all of its arms.',
      'Ben felt his heart beating fast. He grabbed his pencil. Very carefully, he drew a small wooden dock on the table. The boat sailed right up to it and stopped.',
      'The octopus climbed up next to the boat and looked at Ben with friendly eyes. Ben drew a small fish next to the octopus. Right away, the fish flicked its tail and began to swim across the table.',
      'For an hour, Ben drew. He drew sea birds, and a sandy beach, and a tiny lighthouse. Everything he drew came alive, all over the kitchen.',
      'When his mother came in to start dinner, the whole table was covered in tiny moving things. She blinked.',
      'Ben smiled. “I made friends,” he said.',
      'His mother looked at him for a long moment. Then she set down her grocery bag and smiled too. “In that case,” she said, “please draw me a cup of tea.”',
      'So Ben did. And it was the best cup of tea his mother had ever tasted.',
    ],
    comprehension: [
      {
        q: 'What did Ben draw first that came to life?',
        options: ['A castle', 'A small boat with a yellow sail', 'A racing car'],
        correctIndex: 1,
      },
      {
        q: 'What did Ben’s mother ask him to draw?',
        options: ['A new pencil', 'A cup of tea', 'A puppy'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-a-bottle-at-sea',
    tier: 3,
    title: 'A Bottle at Sea',
    cover: 'bottle-sea',
    accent: '#3590a8',
    paragraphs: [
      'Sofia lived in a small town by the sea, with steep streets and white houses and bright blue shutters. Every morning before school, she would walk down to the harbor to look at the water.',
      'On her ninth birthday, her uncle gave her a special gift: a small empty glass bottle, with a tight cork stopper. “For sending messages,” he said with a wink.',
      'That evening, Sofia sat by her window and thought carefully. She wrote a short note on a piece of paper:',
      '“Hello, whoever finds this. My name is Sofia. I am nine years old. I have a brown cat named Olive. I love the sea, and I love stories. Please write back if you can.”',
      'She rolled the paper neatly and slipped it inside the bottle. She pushed the cork in tight.',
      'The next morning, Sofia walked all the way to the end of the long stone pier. The wind tugged at her hair. The waves were big and blue. She held the bottle in both hands and looked at the wide ocean.',
      '“Goodbye, little bottle,” she whispered. “Travel safely.”',
      'She threw it as far as she could. It splashed into the waves and bobbed away.',
      'For weeks, Sofia thought about her bottle. Where was it? Was it still floating? Had a kind person found it? She watched the horizon every afternoon, but no answer came.',
      'A year passed. Sofia turned ten. She was almost beginning to forget about the bottle, when one afternoon, the postman brought a letter to her door. The envelope was thick and warm, with strange colorful stamps and crinkly edges.',
      'Sofia tore it open. Inside was a letter, written in careful, slightly clumsy handwriting, in a language she did not know. But folded inside was a translation, neatly written in pencil.',
      '“Dear Sofia,” the letter said. “My name is Akemi. I live on a small island called Hatsushima, very far from your country. My grandfather found your bottle on our beach. We were amazed it traveled so far. I am eight years old. I also have a cat, but mine is black, and her name is Mochi. I also love stories.',
      '“My favorite story is about a fisherman who befriends a turtle. Please tell me one of yours.',
      '“With friendship from across the sea,',
      'Akemi.”',
      'Sofia read the letter three times. Her hands were trembling, but she was smiling so wide her cheeks hurt.',
      'That night, she sat down with a fresh piece of paper. She had a story to tell, and a new friend to tell it to. Outside her window, the waves kept moving, slowly and patiently, the way they had moved for a thousand years.',
    ],
    comprehension: [
      {
        q: 'What gift did Sofia get for her ninth birthday?',
        options: [
          'A book about the sea',
          'A small empty glass bottle',
          'A new cat',
        ],
        correctIndex: 1,
      },
      {
        q: 'Who finally answered Sofia’s message?',
        options: [
          'A sailor named Mochi',
          'A girl named Akemi from a faraway island',
          'Her uncle, as a joke',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-my-little-dog',
    tier: 0,
    title: 'My Little Dog',
    cover: 'dog',
    accent: '#9a7b4f',
    paragraphs: [
      'I have a little dog. His name is Spot.',
      'Spot is brown and white. He has soft ears and a happy tail.',
      'Spot can run. Spot can jump. Spot can sit when I ask him.',
      'He likes to play in the park. He likes to play with me.',
      'At night, Spot sleeps on my bed. He is warm and soft.',
      'I love my little dog. And my little dog loves me.',
    ],
    comprehension: [
      {
        q: 'What is the dog’s name?',
        options: ['Spot', 'Sam', 'Max'],
        correctIndex: 0,
      },
      {
        q: 'Where does Spot sleep at night?',
        options: ['In the park', 'On my bed', 'In a box'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-the-big-red-apple',
    tier: 0,
    title: 'The Big Red Apple',
    cover: 'apple',
    accent: '#b1493f',
    paragraphs: [
      'Here is a big red apple. The apple is round and shiny.',
      'The apple is sweet. It smells very good.',
      'Mom cuts the apple with a knife. Now there are four pieces.',
      'She gives me a piece. She gives Dad a piece.',
      'She gives my sister a piece. She keeps one piece too.',
      'We all eat the apple together. The big red apple is yummy.',
    ],
    comprehension: [
      {
        q: 'What color is the apple?',
        options: ['Green', 'Red', 'Yellow'],
        correctIndex: 1,
      },
      {
        q: 'How many pieces did Mom cut?',
        options: ['Two', 'Four', 'Six'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'en-a-sunny-day',
    tier: 0,
    title: 'A Sunny Day',
    cover: 'sun',
    accent: '#d99a2b',
    paragraphs: [
      'Today is a sunny day. The sky is big and blue.',
      'The sun is warm and bright. I feel happy.',
      'I put on my hat. I go outside to play.',
      'I run on the soft green grass. I jump up high.',
      'A little bird sings in a tree. The bird sounds happy too.',
      'I sing with the bird. What a nice, sunny day!',
    ],
    comprehension: [
      {
        q: 'What is the weather like today?',
        options: ['Rainy', 'Sunny', 'Snowy'],
        correctIndex: 1,
      },
      {
        q: 'What sings in the tree?',
        options: ['A bird', 'A cat', 'The wind'],
        correctIndex: 0,
      },
    ],
  },
];

export const enStories: Story[] = raw.map((s) => ({
  ...s,
  language: 'en',
  wordCount: countWords(s.paragraphs),
  source: 'bundled',
}));
