import type { Story } from '../types';
import { countWords } from '../lib/words';

const raw: Omit<Story, 'wordCount' | 'language' | 'source'>[] = [
  {
    id: 'es-mochi-a-medianoche',
    tier: 1,
    title: 'Mochi a medianoche',
    emoji: '🐱',
    accent: '#7a5a3a',
    paragraphs: [
      'Toda la casa dormía. Las luces estaban apagadas y las cortinas cerradas. Mochi la gatita abrió sus grandes ojos verdes. Era la hora de su aventura secreta de medianoche.',
      'Saltó suavemente de la cama caliente donde Lily dormía. Sus patas no hacían ningún ruido en el suelo de madera. Bajó por el pasillo oscuro, pasando junto a las puertas abiertas de las habitaciones. La luna entraba por la ventana de la cocina como un gran río de plata.',
      'En la cocina, Mochi encontró una bolsa de papel en el suelo. Las bolsas de papel eran su cosa favorita en el mundo entero. La olfateó y luego saltó dentro de un brinco rápido. Cris, cris, cris. La bolsa se movió y tembló. Después, su pequeña nariz negra asomó, llena de orgullo.',
      'Afuera, un búho cantó en algún lugar entre los árboles. Uh. Uh. Mochi inclinó la cabeza y escuchó con mucha atención. Quería ver al búho. Caminó hasta la puerta de atrás y miró a través de la pequeña puerta para gatos.',
      'El jardín estaba lleno de sombras misteriosas. Un arbusto se movió suavemente con el viento. Un pequeño insecto pasó muy rápido. La cola de Mochi se agitó de emoción. Pero hacía un poco de frío afuera, y ella no era tan valiente esa noche.',
      'Se dio la vuelta y caminó hacia la cocina. Comió tres pedacitos de comida seca de su tazón. Luego subió las escaleras despacio, pata tras pata.',
      'Arriba, en la habitación, Lily seguía profundamente dormida. Mochi se hizo un ovillo en la almohada a su lado, como una nube suave y cálida. Cerró sus ojos verdes. Su aventura de medianoche había terminado por esta noche.',
    ],
    comprehension: [
      {
        q: '¿Qué encontró Mochi en la cocina?',
        options: ['Un cuenco de leche', 'Una bolsa de papel', 'Un juguete'],
        correctIndex: 1,
      },
      {
        q: '¿Por qué Mochi no salió afuera?',
        options: [
          'La puerta estaba cerrada con llave',
          'Hacía frío y ella no era tan valiente',
          'Lily la llamó',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'es-el-barco-de-papel',
    tier: 2,
    title: 'El barco de papel',
    emoji: '⛵',
    accent: '#3a6a9a',
    paragraphs: [
      'Cuando por fin paró de llover, Teo salió a la calle con sus botas amarillas nuevas y un pequeño barco de papel plegado. El barco tenía una vela azul muy alta, dibujada con mucho cuidado por su abuela con un rotulador. La calle estaba llena de charcos, pero Teo tenía un plan mucho más grande en mente.',
      'Caminó por el sendero hasta el pequeño arroyo que corría detrás del viejo muro de piedra. El agua se movía suavemente después de la lluvia, llevando hojas y ramitas como diminutos pasajeros. Teo se agachó en la orilla y sujetó su barco de papel con mucho cuidado, con las dos manos.',
      '—Adiós, barco pequeño —susurró—. Buen viaje.',
      'Lo puso sobre el agua. El barco tambaleó. Por un instante, se inclinó hacia un lado, y Teo casi lo agarró de vuelta. Después encontró su equilibrio, y el arroyo lo llevó hacia adelante, despacio y valiente.',
      'Teo caminó por la orilla mirando su barco. Pasó por delante de una piedra marrón que parecía exactamente una tortuga dormida. Giró una vez alrededor de una mancha de musgo verde. Una pequeña rana lo observó desde la hierba con sus ojos negros y brillantes, pero el barco siguió adelante, con su vela azul bien alta.',
      'Un poco más allá, el arroyo se dividió en dos. El barco dudó un momento, balanceándose en el medio. Luego eligió el camino de la derecha, el que pasaba por debajo de un pequeño puente de madera. Teo corrió para seguirlo, salpicando con sus botas amarillas en los charcos.',
      'Pasado el puente, el arroyo se abría en una poza más ancha y soleada. Los nenúfares flotaban sobre el agua como platos verdes. Una libélula de alas azules muy brillantes bajó a inspeccionar al nuevo visitante. El barco de papel cruzó la poza con valentía, como un barco de verdad en un océano de verdad.',
      'Al otro lado, el arroyo se metía bajo un enredo de arbustos y desaparecía. Teo no podía seguirlo más lejos. Se quedó allí, con las manos en los bolsillos, viendo cómo el último pequeño destello de papel desaparecía entre las hojas verdes.',
      'Su abuela le había dicho que los barcos de papel solo navegan una vez. Salen para su propia aventura, y no vuelven. Teo no se sintió triste. Se sintió feliz y un poco orgulloso. En algún lugar del bosque, su pequeña vela azul seguía avanzando, hacia donde quería ir el agua.',
    ],
    comprehension: [
      {
        q: '¿Quién dibujó la vela del barco?',
        options: ['Su mamá', 'Su abuela', 'Su maestro'],
        correctIndex: 1,
      },
      {
        q: '¿Cómo se sentía Teo al final de la historia?',
        options: [
          'Triste y solo',
          'Feliz y un poco orgulloso',
          'Cansado y enfadado',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'es-el-telescopio-del-abuelo',
    tier: 2,
    title: 'El telescopio del abuelo',
    emoji: '🔭',
    accent: '#3d3a6e',
    paragraphs: [
      'Era la noche favorita de Maya en todo el año. Cada mes de julio, se quedaba a dormir en la pequeña casa del abuelo, en la colina, y siempre hacían juntos la misma cosa maravillosa.',
      'Después de cenar, el abuelo abrió el armario debajo de la escalera y sacó un telescopio largo de latón. Era viejo y estaba un poco rayado, pero brillaba bajo la luz de la lámpara de la cocina. El abuelo limpió con mucho cuidado el ocular redondo con su suave paño azul.',
      '—¿Las nubes todavía esconden el cielo? —preguntó Maya, asomándose por la ventana.',
      '—Ya no —dijo el abuelo con un pequeño guiño—. Ven afuera a ver.',
      'Salieron al aire fresco de la tarde. La hierba ya estaba húmeda de rocío. Maya llevaba el viejo jersey de lana de su abuela, calentito y que olía un poco a canela. El abuelo montó el telescopio sobre sus tres patas de madera muy firmes y lo apuntó hacia el cielo oscuro.',
      'Lo primero que miraron fue la luna. A través del telescopio, la luna ya no era solo un círculo blanco y plano. Era un mundo redondo y lleno de bultos, con montañas y cráteres. Maya podía ver la sombra larga de un acantilado. Podía ver los pequeños mares oscuros por los que la luna era famosa. Contuvo la respiración.',
      '—Parece un sitio por donde yo podría caminar —susurró.',
      '—Algún día, quizá —dijo el abuelo.',
      'Después, giró el telescopio hacia un pequeño grupo de estrellas brillantes. Se llamaban las Siete Hermanas, le explicó. A Maya le parecían un puñado de pequeñas joyas esparcidas sobre una tela azul.',
      'Luego, encontraron un planeta, bajo y anaranjado, cerca del horizonte. El abuelo dijo que se llamaba Marte. A través del telescopio, era un puntito borroso, no tan claro como la luna. Pero a Maya no le importó. Marte también era un mundo entero, solo que muy, muy lejos.',
      'Cuando los ojos de Maya empezaron a sentirse cansados, el abuelo le dejó mirar una última cosa. Giró el telescopio hacia una pequeña mancha pálida entre dos estrellas. La llamó una galaxia. Le explicó que estaba tan lejos que la luz que les llegaba había estado viajando durante más de dos millones de años.',
      'Maya no dijo nada durante un buen rato. Pensó en la luz, en las distancias, y en su propio pequeño lugar en todo aquello.',
      'El abuelo apoyó suavemente su mano grande y cálida en su hombro. Maya se recostó contra él. Encima de ellos, todo el cielo seguía girando, como siempre había hecho, y como siempre haría.',
    ],
    comprehension: [
      {
        q: '¿Qué objeto especial sacó el abuelo del armario?',
        options: [
          'Un libro de estrellas',
          'Un telescopio largo de latón',
          'Unos prismáticos',
        ],
        correctIndex: 1,
      },
      {
        q: '¿Cuánto tiempo lleva viajando la luz de la galaxia?',
        options: [
          'Solo unos minutos',
          'Unos mil años',
          'Más de dos millones de años',
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: 'es-el-aprendiz-del-faro',
    tier: 3,
    title: 'El aprendiz del faro',
    emoji: '💡',
    accent: '#a85d2e',
    paragraphs: [
      'Sam visitaba el viejo faro cada verano. El guardián, el señor Brennan, tenía cejas blancas y espesas, ojos marrones muy amables, y una risa que sonaba un poco como el chirrido de una puerta. Llevaba cuidando la gran luz desde hacía treinta y seis años.',
      'Aquel verano, Sam por fin era lo bastante alto para subir solo a la sala de la lámpara. Había practicado con la larga escalera en espiral durante tres días, contando cada escalón en voz alta mientras subía. Eran ciento sesenta y ocho en total.',
      'El cuarto día de Sam, el tiempo cambió. El cielo se llenó de pesadas nubes grises, y abajo el mar empezó a lanzar espuma blanca contra las rocas. Por la tarde, el viento ya hacía temblar las ventanas de la pequeña casa de piedra del guardián.',
      'El señor Brennan salió de la cocina con una taza de metal llena de té. —Esta noche va a ser una noche atareada —dijo en voz baja—. La lámpara debe brillar con más fuerza que nunca. Todavía hay barcos de pesca ahí fuera.',
      'Sam lo miró con ojos serios. —¿Puedo ayudar?',
      'El señor Brennan sonrió. —Sí, puedes. Esta noche, serás mi aprendiz.',
      'Subieron juntos la larga escalera, despacio, porque la tormenta hacía que el faro pareciera un poco como un árbol en el viento. Arriba del todo, la sala de la lámpara estaba caliente y llena de una suave luz dorada. La gran lámpara en sí era una hermosa máquina, hecha toda de latón pulido y cristal curvado. Giraba con suavidad, lanzando un largo rayo brillante hacia el cielo que iba oscureciendo.',
      'El trabajo de Sam era pulir cada uno de los paneles de cristal con un paño blanco suave. Trabajó con mucho cuidado, un panel a la vez, asegurándose de no dejar ninguna marca. El señor Brennan revisó cada engranaje y añadió una pequeña gota de aceite a las piezas que lo necesitaban. Fuera, el viento aullaba y la lluvia golpeaba, pero dentro de la sala de la lámpara, todo seguía en calma y estable.',
      'Cuando la noche cayó del todo, Sam apoyó la nariz contra el cristal frío. Abajo, el mar negro estaba salvaje, lleno de olas que rompían. Muy lejos, cerca del borde de la tormenta, vio una pequeña luz que se movía. Era un barco.',
      '—¡Mira! —dijo Sam—. ¿Estarán bien?',
      'El señor Brennan se puso a su lado y observó. La pequeña luz se balanceaba en las olas, pero no se apagaba. Avanzaba muy despacio, muy despacio, hacia su rayo de luz.',
      '—Se dirigen al puerto —dijo el señor Brennan—. Nuestra lámpara les muestra el camino seguro.',
      'Sam se sintió muy pequeño y muy importante a la vez. Se quedó allí mucho tiempo, viendo cómo la pequeña luz crecía un poquito. El viento seguía aullando. Las olas seguían rompiendo. Pero la lámpara seguía girando, lenta, brillante y estable, como había hecho cada noche durante más de cien años.',
      'Cuando la tormenta finalmente se alejó, cerca de medianoche, Sam casi se había quedado dormido en el pequeño taburete de madera junto a la puerta. El señor Brennan lo levantó suavemente y lo bajó por la escalera en espiral, escalón a escalón. Fuera, el cielo se aclaraba. En algún lugar del mar, un pequeño barco de pesca llegaba por fin a la seguridad del puerto.',
    ],
    comprehension: [
      {
        q: '¿Cuántos escalones llevan a la sala de la lámpara?',
        options: ['Treinta y seis', 'Cien', 'Ciento sesenta y ocho'],
        correctIndex: 2,
      },
      {
        q: '¿Cuál era el trabajo de Sam esa noche?',
        options: [
          'Pulir los paneles de cristal',
          'Encender la lámpara con una cerilla',
          'Vigilar desde la cocina',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'es-el-zorro-y-el-guante',
    tier: 1,
    title: 'El zorro y el guante',
    emoji: '🦊',
    accent: '#b86a4d',
    paragraphs: [
      'Nevaba suavemente en el bosque. Una pequeña zorra roja, que se llamaba Pim, buscaba algo de comer. Sus patas dejaban pequeñas huellas en la nieve recién caída.',
      'Debajo de un pino alto, Pim encontró algo extraño. Era cálido, de lana, y de un azul muy brillante. Era el guante de un niño, con una pequeña estrella blanca cosida delante.',
      'Pim lo olfateó con cuidado. Olía a persona, a perro pequeño, y un poquito a galletas. Debe de ser de alguien, pensó.',
      'Pim recogió el guante con suavidad entre sus dientes. Trotó entre los árboles nevados, pasó junto al estanque helado, y llegó al borde del bosque. Allí, vio una pequeña casa de madera con humo saliendo de la chimenea.',
      'Una niña pequeña con un abrigo rojo brillante estaba haciendo un muñeco de nieve en el patio. Llevaba un guante azul en la mano izquierda. Su mano derecha estaba desnuda y rosa por el frío.',
      'Pim se detuvo al borde del patio. Era un poco tímida. Colocó el guante con cuidado en la nieve, y luego dio tres pasos hacia atrás, sin hacer ruido.',
      'La niña la vio y se quedó sin aliento. Se acercó despacio, recogió el guante, y sonrió. Después se lo puso de nuevo en su mano fría y rosada.',
      '—Gracias —susurró.',
      'Pim agitó su cola peluda una sola vez. Luego se dio la vuelta y corrió de vuelta al bosque nevado, con su misión cumplida.',
    ],
    comprehension: [
      {
        q: '¿Cómo era el guante que encontró Pim?',
        options: [
          'Rojo con una luna',
          'Azul con una estrella blanca',
          'A rayas',
        ],
        correctIndex: 1,
      },
      {
        q: '¿Cómo le devolvió Pim el guante a la niña?',
        options: [
          'Lo dejó en la puerta de la casa',
          'Lo colocó en la nieve y dio pasos atrás',
          'Se lo entregó en la mano',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'es-el-caracol-del-jardin',
    tier: 1,
    title: 'El caracol del jardín',
    emoji: '🌱',
    accent: '#5f8a4d',
    paragraphs: [
      'Lila adoraba el jardín de su abuela. Había fresas, tomates rojos, y altos girasoles amarillos que giraban su cara para seguir al sol.',
      'Una mañana soleada, Lila notó un pequeñísimo visitante en la hoja de su fresa favorita. Era un caracol marrón pequeño, con una concha en espiral. Estaba comiendo un trocito de hoja.',
      '—Hola —dijo Lila en voz baja—. ¿Estás ayudando en el jardín?',
      'El caracol no respondió, claro. Pero movió despacio sus pequeñas antenas.',
      'La abuela salió con una regadera grande. —Ah —rio—, ya conociste al señor Pepino.',
      '—¿El señor Pepino? —dijo Lila.',
      '—Así lo llamo yo. Vive en este jardín desde hace mucho, mucho tiempo. Se come unas hojas, pero también es un pequeñísimo jardinero. Ayuda a las plantas a crecer.',
      'Lila miró al caracol con un nuevo respeto. Se movía muy despacio. Dejaba detrás de él un rastro brillante, como de plata.',
      'Por la tarde, Lila le llevó un trozo fresco de lechuga de la cocina. Lo puso con cuidado cerca de la fresa. A la mañana siguiente, la lechuga casi había desaparecido, y el señor Pepino estaba sentado encima, muy contento.',
      'Lila sonrió. Ella y el señor Pepino iban a ser muy buenos amigos, decidió. Aunque caminarían por el jardín a velocidades muy diferentes.',
    ],
    comprehension: [
      {
        q: '¿Cómo se llama el caracol?',
        options: ['El señor Tomate', 'El señor Pepino', 'El señor Concha'],
        correctIndex: 1,
      },
      {
        q: '¿Qué le llevó Lila al caracol?',
        options: ['Una fresa', 'Un trozo de lechuga', 'Un poco de agua'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'es-el-dibujo-que-cobro-vida',
    tier: 2,
    title: 'El dibujo que cobró vida',
    emoji: '🎨',
    accent: '#7a4a9a',
    paragraphs: [
      'Era un sábado lluvioso, y Ben no tenía nada que hacer. Estaba sentado a la mesa de la cocina con su viejo lápiz de madera y una hoja blanca recién sacada. Fuera, la lluvia golpeaba la ventana como un tambor adormilado.',
      'Ben decidió dibujar algo especial. Dibujó una pequeña isla redonda, con una palmera alta encima. Dibujó un barquito con una vela amarilla. Dibujó un pulpo amable que saludaba desde el agua azul.',
      'Cuando terminó, dejó el lápiz y se estiró. Y entonces ocurrió algo muy extraño.',
      'El barquito de su dibujo empezó a moverse. Se balanceaba suavemente, como sobre olas de verdad. La palmera ondeaba. Y el pulpo le guiñó un ojo redondo.',
      'Ben contuvo la respiración. Se quedó muy quieto, mirando.',
      'El barco navegó despacio por la hoja, salió por el borde, y se deslizó sobre la mesa. Avanzó por la cocina, dejando un rastro mojado pequeñísimo. El pulpo lo siguió a saltitos, agitando todos sus brazos.',
      'Ben sentía el corazón latir muy fuerte. Agarró su lápiz. Con mucho cuidado, dibujó un pequeño muelle de madera sobre la mesa. El barco llegó hasta allí y se detuvo.',
      'El pulpo subió junto al barco y miró a Ben con ojos amables. Ben dibujó un pez pequeño al lado del pulpo. Al instante, el pez agitó la cola y empezó a nadar por la mesa.',
      'Durante una hora, Ben dibujó. Dibujó gaviotas, una playa de arena, y un faro chiquito. Todo lo que dibujaba cobraba vida, por toda la cocina.',
      'Cuando su madre entró para empezar la cena, toda la mesa estaba cubierta de pequeñas cosas que se movían. Ella parpadeó.',
      'Ben sonrió. —He hecho amigos —dijo.',
      'Su madre lo miró durante un buen rato. Después dejó la bolsa de la compra y también sonrió. —En ese caso —dijo—, dibújame una taza de té, por favor.',
      'Así que Ben lo hizo. Y fue la mejor taza de té que su madre había probado nunca.',
    ],
    comprehension: [
      {
        q: '¿Qué fue lo primero que Ben dibujó que cobró vida?',
        options: [
          'Un castillo',
          'Un barquito con una vela amarilla',
          'Un coche de carreras',
        ],
        correctIndex: 1,
      },
      {
        q: '¿Qué le pidió la madre de Ben que dibujara?',
        options: ['Un lápiz nuevo', 'Una taza de té', 'Un cachorro'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'es-una-botella-en-el-mar',
    tier: 3,
    title: 'Una botella en el mar',
    emoji: '💌',
    accent: '#3590a8',
    paragraphs: [
      'Sofía vivía en un pueblo pequeño junto al mar, con calles empinadas, casas blancas y contraventanas de un azul brillante. Cada mañana antes del colegio, bajaba hasta el puerto para mirar el agua.',
      'En su noveno cumpleaños, su tío le hizo un regalo especial: una pequeña botella de cristal vacía, con un tapón de corcho bien apretado. —Para enviar mensajes —dijo con un guiño.',
      'Esa tarde, Sofía se sentó junto a su ventana y pensó con cuidado. Escribió una nota corta en un trozo de papel:',
      '«Hola, quien sea que encuentre esto. Me llamo Sofía. Tengo nueve años. Tengo una gata marrón que se llama Olivia. Me encanta el mar, y me encantan las historias. Por favor, contéstame si puedes.»',
      'Enrolló el papel con cuidado y lo metió dentro de la botella. Apretó bien el corcho.',
      'A la mañana siguiente, Sofía caminó hasta el final del largo muelle de piedra. El viento le tiraba del pelo. Las olas eran grandes y azules. Sostuvo la botella con las dos manos y miró el ancho océano.',
      '—Adiós, botella pequeña —susurró—. Buen viaje.',
      'La lanzó tan lejos como pudo. La botella cayó en las olas y se alejó flotando.',
      'Durante semanas, Sofía pensó en su botella. ¿Dónde estaba? ¿Seguía flotando? ¿La habría encontrado alguna persona amable? Miraba el horizonte cada tarde, pero no llegaba ninguna respuesta.',
      'Pasó un año. Sofía cumplió diez. Casi estaba empezando a olvidarse de la botella, cuando una tarde, el cartero trajo una carta a su puerta. El sobre era grueso y cálido, con sellos extraños y de colores, y bordes un poco arrugados.',
      'Sofía lo abrió. Dentro había una carta, escrita con una letra cuidadosa y un poco torpe, en un idioma que ella no conocía. Pero doblada dentro había una traducción, escrita con esmero a lápiz.',
      '«Querida Sofía», decía la carta. «Me llamo Akemi. Vivo en una pequeña isla que se llama Hatsushima, muy lejos de tu país. Mi abuelo encontró tu botella en nuestra playa. Nos quedamos asombrados de que hubiera viajado tan lejos. Tengo ocho años. Yo también tengo una gata, pero la mía es negra y se llama Mochi. A mí también me encantan las historias.',
      '«Mi historia favorita es la de un pescador que se hace amigo de una tortuga. Por favor, cuéntame una de las tuyas.',
      '«Con amistad desde el otro lado del mar,',
      'Akemi.»',
      'Sofía leyó la carta tres veces. Le temblaban las manos, pero sonreía tanto que le dolían las mejillas.',
      'Esa noche, se sentó con una hoja de papel nueva. Tenía una historia que contar, y una nueva amiga a la que contársela. Fuera de su ventana, las olas seguían moviéndose, despacio y con paciencia, igual que se habían movido durante mil años.',
    ],
    comprehension: [
      {
        q: '¿Qué regalo recibió Sofía por su noveno cumpleaños?',
        options: [
          'Un libro sobre el mar',
          'Una pequeña botella de cristal vacía',
          'Una gata nueva',
        ],
        correctIndex: 1,
      },
      {
        q: '¿Quién respondió finalmente al mensaje de Sofía?',
        options: [
          'Un marinero llamado Mochi',
          'Una niña llamada Akemi de una isla lejana',
          'Su tío, como una broma',
        ],
        correctIndex: 1,
      },
    ],
  },
];

export const esStories: Story[] = raw.map((s) => ({
  ...s,
  language: 'es',
  wordCount: countWords(s.paragraphs),
  source: 'bundled',
}));
