import type { Story } from '../types';
import { countWords } from '../lib/words';

const raw: Omit<Story, 'wordCount' | 'language' | 'source'>[] = [
  {
    id: 'fr-mochi-a-minuit',
    tier: 1,
    title: 'Mochi à minuit',
    emoji: '🐱',
    accent: '#7a5a3a',
    paragraphs: [
      'Tout le monde dans la maison dormait. Les lumières étaient éteintes, et les rideaux étaient tirés. Mochi le chaton ouvrit ses grands yeux verts. C’était l’heure de son aventure secrète de minuit.',
      'Elle sauta doucement du lit chaud où Lily dormait. Ses pattes ne faisaient aucun bruit sur le plancher de bois. Elle descendit le long couloir sombre, passa devant les portes des chambres ouvertes. La lune entrait par la fenêtre de la cuisine, comme un grand fleuve d’argent.',
      'Dans la cuisine, Mochi trouva un sac en papier par terre. Les sacs en papier étaient sa chose préférée au monde. Elle le renifla, puis sauta dedans d’un bond rapide. Crrr, crrr, crrr. Le sac bougea et trembla. Puis son petit nez noir sortit, fier comme tout.',
      'Dehors, un hibou chanta quelque part dans les arbres. Hou. Hou. Mochi pencha la tête et écouta très attentivement. Elle voulait voir le hibou. Elle marcha jusqu’à la porte de derrière et regarda à travers la petite porte pour chats.',
      'Le jardin était plein d’ombres mystérieuses. Un buisson bougeait doucement dans le vent. Un petit insecte passa très vite. La queue de Mochi frétilla d’excitation. Mais il faisait un peu froid dehors, et elle n’était pas si courageuse ce soir.',
      'Elle se retourna et marcha jusqu’à la cuisine. Elle mangea trois petits morceaux de croquettes dans son bol. Puis elle monta les escaliers lentement, patte par patte.',
      'En haut, dans la chambre, Lily dormait toujours profondément. Mochi se roula en boule sur l’oreiller à côté d’elle, comme un nuage doux et chaud. Elle ferma ses yeux verts. Son aventure de minuit était finie pour ce soir.',
    ],
    comprehension: [
      {
        q: 'Qu’est-ce que Mochi a trouvé dans la cuisine ?',
        options: ['Un bol de lait', 'Un sac en papier', 'Un jouet'],
        correctIndex: 1,
      },
      {
        q: 'Pourquoi Mochi n’est-elle pas sortie ?',
        options: [
          'La porte était fermée à clé',
          'Il faisait froid et elle n’était pas si courageuse',
          'Lily l’a appelée',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'fr-le-bateau-en-papier',
    tier: 2,
    title: 'Le bateau en papier',
    emoji: '⛵',
    accent: '#3a6a9a',
    paragraphs: [
      'Quand la pluie s’arrêta enfin, Théo sortit dehors avec ses bottes jaunes toutes neuves et un petit bateau en papier plié. Le bateau avait une grande voile bleue, dessinée avec soin au feutre par sa grand-mère. La rue était pleine de flaques, mais Théo avait un plan bien plus grand en tête.',
      'Il descendit le chemin jusqu’au petit ruisseau qui coulait derrière le vieux mur de pierre. L’eau avançait doucement après la pluie, emportant des feuilles et des brindilles comme de minuscules passagers. Théo s’accroupit au bord et tint son bateau de papier avec ses deux mains.',
      '« Au revoir, petit bateau, murmura-t-il. Bon voyage. »',
      'Il le posa sur l’eau. Le bateau vacilla. Pendant un instant, il pencha sur le côté, et Théo faillit le rattraper. Puis il trouva son équilibre, et le ruisseau l’emporta vers l’avant, lentement et bravement.',
      'Théo marcha le long de la berge en regardant son bateau. Il passa devant un rocher brun qui ressemblait exactement à une tortue endormie. Il tourna une fois autour d’une touffe de mousse verte. Une petite grenouille le regarda depuis l’herbe avec ses yeux noirs et brillants, mais le bateau continua tout droit, sa grande voile bleue dressée bien haut.',
      'Un peu plus loin, le ruisseau se sépara en deux. Le bateau hésita un moment, en flottant au milieu. Puis il choisit le chemin de droite, celui qui passait sous un petit pont de bois. Théo courut pour le suivre, ses bottes jaunes éclaboussant dans les flaques.',
      'Après le pont, le ruisseau s’ouvrit sur un bassin plus large et ensoleillé. Des nénuphars flottaient sur l’eau comme des assiettes vertes. Une libellule aux ailes bleu vif descendit pour inspecter le nouvel arrivé. Le bateau de papier traversa le bassin courageusement, comme un vrai navire sur un vrai océan.',
      'De l’autre côté, le ruisseau se glissait sous un fouillis de buissons et disparaissait. Théo ne pouvait pas le suivre plus loin. Il resta là, les mains dans les poches, à regarder le dernier petit éclat de papier disparaître dans les feuilles vertes.',
      'Sa grand-mère lui avait dit que les bateaux en papier ne voyagent qu’une seule fois. Ils partent pour leur propre aventure, et ils ne reviennent pas. Théo n’était pas triste. Il était heureux et un peu fier. Quelque part dans les bois, sa petite voile bleue continuait à avancer, là où l’eau voulait aller.',
    ],
    comprehension: [
      {
        q: 'Qui a dessiné la voile du bateau ?',
        options: ['Sa maman', 'Sa grand-mère', 'Son maître'],
        correctIndex: 1,
      },
      {
        q: 'Comment Théo se sentait-il à la fin de l’histoire ?',
        options: [
          'Triste et seul',
          'Heureux et un peu fier',
          'Fatigué et en colère',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'fr-la-lunette-de-papi',
    tier: 2,
    title: 'La lunette de Papi',
    emoji: '🔭',
    accent: '#3d3a6e',
    paragraphs: [
      'C’était la nuit préférée de Maya dans toute l’année. Chaque mois de juillet, elle dormait chez Papi, dans sa petite maison sur la colline, et ils faisaient toujours la même chose merveilleuse ensemble.',
      'Après le dîner, Papi ouvrit le placard sous l’escalier et sortit une longue lunette en cuivre. Elle était vieille, et un peu rayée, mais elle brillait sous la lumière de la lampe de la cuisine. Papi nettoya soigneusement le petit oculaire rond avec son chiffon bleu doux.',
      '« Est-ce que les nuages cachent encore le ciel ? » demanda Maya en regardant par la fenêtre.',
      '« Plus du tout, dit Papi avec un petit clin d’œil. Viens dehors et regarde. »',
      'Ils sortirent dans l’air frais du soir. L’herbe était déjà humide de rosée. Maya portait le vieux pull en laine de sa grand-mère, chaud et qui sentait un peu la cannelle. Papi installa la lunette sur ses trois pieds en bois bien solides et la pointa vers le ciel sombre.',
      'La première chose qu’ils regardèrent fut la lune. À travers la lunette, la lune n’était plus seulement un cercle blanc et plat. C’était un monde rond et bosselé, plein de montagnes et de cratères. Maya pouvait voir la longue ombre d’une falaise. Elle pouvait voir les petites mers sombres pour lesquelles la lune était célèbre. Elle retint son souffle.',
      '« On dirait un endroit où je pourrais marcher », chuchota-t-elle.',
      '« Un jour, peut-être », dit Papi.',
      'Ensuite, il tourna la lunette vers un petit groupe d’étoiles brillantes. Elles s’appelaient les Sept Sœurs, expliqua-t-il. Pour Maya, elles ressemblaient à une poignée de petits bijoux jetés sur un tissu bleu.',
      'Après cela, ils trouvèrent une planète, basse et orange près de l’horizon. Papi dit qu’elle s’appelait Mars. À travers la lunette, c’était un petit point flou, pas aussi net que la lune. Mais Maya ne fut pas déçue. Mars était un monde entier elle aussi, simplement très, très loin.',
      'Quand les yeux de Maya commencèrent à être fatigués, Papi lui laissa regarder une dernière chose. Il tourna la lunette vers une petite tache pâle entre deux étoiles. Il l’appela une galaxie. Il expliqua qu’elle était si loin que la lumière qui arrivait jusqu’à eux voyageait depuis plus de deux millions d’années.',
      'Maya ne dit rien pendant un long moment. Elle pensa à la lumière, et aux distances, et à sa propre petite place dans tout cela.',
      'Papi posa doucement sa grande main chaude sur son épaule. Maya s’appuya contre lui. Au-dessus d’eux, le ciel tout entier continuait à tourner, comme il l’avait toujours fait, et comme il le ferait toujours.',
    ],
    comprehension: [
      {
        q: 'Quel objet spécial Papi a-t-il sorti du placard ?',
        options: [
          'Un livre sur les étoiles',
          'Une longue lunette en cuivre',
          'Une paire de jumelles',
        ],
        correctIndex: 1,
      },
      {
        q: 'Depuis combien de temps la lumière de la galaxie voyage-t-elle ?',
        options: [
          'Quelques minutes',
          'Environ mille ans',
          'Plus de deux millions d’années',
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: 'fr-lapprenti-du-phare',
    tier: 3,
    title: 'L’apprenti du phare',
    emoji: '💡',
    accent: '#a85d2e',
    paragraphs: [
      'Sam visitait le vieux phare chaque été. Le gardien, monsieur Brennan, avait des sourcils blancs et broussailleux, des yeux bruns très gentils, et un rire qui ressemblait un peu au grincement d’une porte. Il gardait la grande lumière allumée depuis trente-six ans.',
      'Cet été, Sam était enfin assez grand pour monter tout seul jusqu’à la salle de la lampe. Il avait pratiqué l’escalier en colimaçon pendant trois jours, en comptant chaque marche à voix haute pendant qu’il montait. Il y en avait cent soixante-huit en tout.',
      'Le quatrième jour de Sam, le temps changea. Le ciel se remplit de gros nuages gris, et la mer en bas commença à lancer de l’écume blanche contre les rochers. Dans l’après-midi, le vent faisait trembler les fenêtres de la petite maison en pierre du gardien.',
      'Monsieur Brennan sortit de la cuisine, tenant une tasse en métal pleine de thé. « La nuit va être bien chargée, dit-il doucement. La lampe doit briller encore plus fort. Il y a encore des bateaux de pêche sortis en mer. »',
      'Sam le regarda avec des yeux sérieux. « Est-ce que je peux t’aider ? »',
      'Monsieur Brennan sourit. « Oui, tu peux. Cette nuit, tu seras mon apprenti. »',
      'Ils montèrent ensemble le long escalier, lentement, car la tempête donnait au phare l’impression d’être un peu comme un arbre dans le vent. Tout en haut, la salle de la lampe était chaude et pleine d’une douce lumière dorée. La grande lampe elle-même était une belle machine, faite tout en cuivre poli et en verre courbé. Elle tournait doucement, envoyant un long rayon brillant dans le ciel qui s’assombrissait.',
      'Le travail de Sam, c’était de nettoyer chacun des panneaux de verre avec un chiffon blanc doux. Il travailla soigneusement, un panneau à la fois, en faisant attention de ne laisser aucune trace. Monsieur Brennan vérifia chaque engrenage et ajouta une petite goutte d’huile aux pièces qui en avaient besoin. Dehors, le vent hurlait et la pluie tambourinait, mais à l’intérieur de la salle de la lampe, tout restait calme et stable.',
      'Quand la nuit tomba vraiment, Sam appuya son nez contre la vitre froide. En bas, la mer noire était sauvage, pleine de vagues qui s’écrasaient. Au loin, près du bord de la tempête, il vit une petite lumière qui bougeait. C’était un bateau.',
      '« Regarde ! dit Sam. Est-ce qu’ils vont bien ? »',
      'Monsieur Brennan se tint à côté de lui et regarda. La petite lumière tanguait dans les vagues, mais elle ne s’éteignait pas. Elle avançait doucement, doucement, vers leur rayon de lumière.',
      '« Ils se dirigent vers le port, dit monsieur Brennan. Notre lampe leur indique le chemin sûr. »',
      'Sam se sentit très petit, et très important, en même temps. Il resta là un long moment, à regarder la petite lumière grandir un tout petit peu. Le vent continuait à hurler. Les vagues continuaient à frapper. Mais la lampe continuait à tourner, lente, brillante et stable, comme elle l’avait fait chaque nuit depuis plus de cent ans.',
      'Quand la tempête s’éloigna enfin, vers minuit, Sam s’était presque endormi sur le petit tabouret en bois près de la porte. Monsieur Brennan le souleva doucement et le porta dans l’escalier en colimaçon, marche après marche. Dehors, le ciel se dégageait. Quelque part en mer, un petit bateau de pêche arrivait enfin à l’abri du port.',
    ],
    comprehension: [
      {
        q: 'Combien de marches mènent à la salle de la lampe ?',
        options: ['Trente-six', 'Cent', 'Cent soixante-huit'],
        correctIndex: 2,
      },
      {
        q: 'Quel était le travail de Sam cette nuit-là ?',
        options: [
          'Nettoyer les panneaux de verre',
          'Allumer la lampe avec une allumette',
          'Surveiller depuis la cuisine',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'fr-le-renard-et-la-moufle',
    tier: 1,
    title: 'Le renard et la moufle',
    emoji: '🦊',
    accent: '#b86a4d',
    paragraphs: [
      'Il neigeait doucement dans la forêt. Une petite renarde rousse, qui s’appelait Pim, cherchait quelque chose à manger. Ses pattes laissaient de petites traces dans la neige toute fraîche.',
      'Sous un grand sapin, Pim trouva quelque chose d’étrange. C’était chaud, et tout en laine, et bleu vif. C’était la moufle d’un enfant, avec une petite étoile blanche cousue sur le devant.',
      'Pim la renifla avec attention. Elle sentait la personne, et un peu le petit chien, et un tout petit peu les biscuits. Cela doit appartenir à quelqu’un, pensa-t-elle.',
      'Pim prit la moufle doucement entre ses dents. Elle trotta à travers les arbres enneigés, passa devant l’étang gelé, et arriva au bord de la forêt. Là, elle voyait une petite maison en bois avec de la fumée qui montait de la cheminée.',
      'Une petite fille en manteau rouge construisait un bonhomme de neige dans la cour. Elle portait une moufle bleue sur sa main gauche. Sa main droite était nue et toute rose à cause du froid.',
      'Pim s’arrêta au bord de la cour. Elle était un peu timide. Elle déposa la moufle avec soin dans la neige, puis recula de trois petits pas, sans bruit.',
      'La petite fille la vit et fit un grand oh. Elle s’avança doucement, ramassa la moufle, et sourit. Puis elle la remit sur sa main froide et rose.',
      '— Merci, chuchota-t-elle.',
      'Pim agita sa queue touffue une seule fois. Puis elle se retourna et repartit en courant dans la forêt enneigée, sa mission accomplie.',
    ],
    comprehension: [
      {
        q: 'Comment était la moufle que Pim a trouvée ?',
        options: [
          'Rouge avec une lune',
          'Bleue avec une étoile blanche',
          'À rayures',
        ],
        correctIndex: 1,
      },
      {
        q: 'Comment Pim a-t-elle rendu la moufle ?',
        options: [
          'Elle l’a posée devant la porte',
          'Elle l’a déposée dans la neige et a reculé',
          'Elle l’a donnée à la petite fille',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'fr-lescargot-du-jardin',
    tier: 1,
    title: 'L’escargot du jardin',
    emoji: '🌱',
    accent: '#5f8a4d',
    paragraphs: [
      'Lila adorait le jardin de sa grand-mère. Il y avait des fraises, des tomates rouges, et de grands tournesols jaunes qui tournaient leur visage pour suivre le soleil.',
      'Un matin ensoleillé, Lila remarqua un tout petit visiteur sur la feuille de son fraisier préféré. C’était un petit escargot brun, avec une coquille en spirale. Il mangeait un minuscule bout de feuille.',
      '— Bonjour, dit Lila tout doucement. Tu aides dans le jardin ?',
      'L’escargot ne répondit pas, bien sûr. Mais il agita lentement ses petites antennes.',
      'Mamie sortit avec un grand arrosoir. — Oh, dit-elle en riant, tu as fait la connaissance de Monsieur Cornichon.',
      '— Monsieur Cornichon ? dit Lila.',
      '— C’est comme ça que je l’appelle. Il vit dans ce jardin depuis très, très longtemps. Il mange quelques feuilles, mais il est aussi un tout petit jardinier. Il aide les plantes à pousser.',
      'Lila regarda l’escargot avec un nouveau respect. Il bougeait si lentement. Il laissait derrière lui une trace toute brillante, comme de l’argent.',
      'L’après-midi, Lila lui apporta un morceau de salade frais de la cuisine. Elle le posa doucement près du fraisier. Le lendemain matin, la salade avait presque disparu, et Monsieur Cornichon était assis dessus, tout content.',
      'Lila sourit. Elle et Monsieur Cornichon allaient être de très bons amis, décida-t-elle. Même s’ils marcheraient dans le jardin à des vitesses très différentes.',
    ],
    comprehension: [
      {
        q: 'Comment s’appelle l’escargot ?',
        options: ['Monsieur Sucre', 'Monsieur Cornichon', 'Monsieur Coquille'],
        correctIndex: 1,
      },
      {
        q: 'Qu’est-ce que Lila a apporté pour l’escargot ?',
        options: ['Une fraise', 'Un morceau de salade', 'De l’eau'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'fr-le-dessin-qui-prend-vie',
    tier: 2,
    title: 'Le dessin qui prend vie',
    emoji: '🎨',
    accent: '#7a4a9a',
    paragraphs: [
      'C’était un samedi pluvieux, et Ben n’avait rien à faire. Il était assis à la table de la cuisine avec son vieux crayon en bois et une feuille blanche toute neuve. Dehors, la pluie tapait contre la vitre comme un tambour endormi.',
      'Ben décida de dessiner quelque chose de spécial. Il dessina une petite île ronde, avec un grand palmier dessus. Il dessina un tout petit bateau avec une voile jaune. Il dessina une gentille petite pieuvre qui faisait coucou depuis l’eau bleue.',
      'Quand il eut terminé, il posa son crayon et s’étira. Et là, quelque chose de très étrange arriva.',
      'Le petit bateau dans son dessin commença à bouger. Il se balançait doucement, comme sur de vraies vagues. Le palmier ondulait. Et la pieuvre lui fit un clin d’œil avec un œil tout rond.',
      'Ben retint son souffle. Il resta complètement immobile, à regarder.',
      'Le bateau navigua doucement à travers la feuille, puis sortit du bord, et glissa sur la table. Il avança à travers la cuisine, en laissant une toute petite trace humide. La pieuvre suivit en flop-flop, en agitant tous ses bras.',
      'Ben sentait son cœur battre très fort. Il attrapa son crayon. Très soigneusement, il dessina un petit ponton en bois sur la table. Le bateau vint s’y amarrer et s’arrêta.',
      'La pieuvre grimpa à côté du bateau et regarda Ben avec des yeux amicaux. Ben dessina un petit poisson à côté de la pieuvre. Aussitôt, le poisson agita sa queue et se mit à nager sur la table.',
      'Pendant une heure, Ben dessina. Il dessina des mouettes, une plage de sable, et un tout petit phare. Tout ce qu’il dessinait prenait vie, partout dans la cuisine.',
      'Quand sa maman entra pour préparer le dîner, toute la table était couverte de petites choses qui bougeaient. Elle cligna des yeux.',
      'Ben sourit. — Je me suis fait des amis, dit-il.',
      'Sa maman le regarda pendant un long moment. Puis elle posa son sac de courses et sourit aussi. — Dans ce cas, dit-elle, dessine-moi une tasse de thé, s’il te plaît.',
      'Alors Ben le fit. Et c’était la meilleure tasse de thé que sa maman ait jamais bue.',
    ],
    comprehension: [
      {
        q: 'Qu’est-ce que Ben a dessiné en premier qui a pris vie ?',
        options: [
          'Un château',
          'Un petit bateau avec une voile jaune',
          'Une voiture',
        ],
        correctIndex: 1,
      },
      {
        q: 'Qu’est-ce que la maman de Ben lui a demandé de dessiner ?',
        options: ['Un nouveau crayon', 'Une tasse de thé', 'Un chiot'],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'fr-une-bouteille-a-la-mer',
    tier: 3,
    title: 'Une bouteille à la mer',
    emoji: '💌',
    accent: '#3590a8',
    paragraphs: [
      'Sofia vivait dans une petite ville au bord de la mer, avec des rues en pente, des maisons blanches et des volets bleu vif. Chaque matin avant l’école, elle descendait jusqu’au port pour regarder l’eau.',
      'Pour son neuvième anniversaire, son oncle lui offrit un cadeau spécial : une petite bouteille en verre vide, avec un bouchon en liège bien serré. — Pour envoyer des messages, dit-il avec un clin d’œil.',
      'Ce soir-là, Sofia s’assit près de sa fenêtre et réfléchit attentivement. Elle écrivit un court message sur un morceau de papier :',
      '« Bonjour, qui que tu sois, toi qui trouveras ce message. Je m’appelle Sofia. J’ai neuf ans. J’ai une chatte brune qui s’appelle Olive. J’adore la mer, et j’adore les histoires. S’il te plaît, réponds-moi si tu peux. »',
      'Elle roula le papier soigneusement et le glissa dans la bouteille. Elle poussa le bouchon bien fort.',
      'Le lendemain matin, Sofia marcha jusqu’au bout de la longue jetée en pierre. Le vent tirait sur ses cheveux. Les vagues étaient grandes et bleues. Elle tenait la bouteille à deux mains et regardait le grand océan.',
      '— Au revoir, petite bouteille, murmura-t-elle. Bon voyage.',
      'Elle la lança aussi loin qu’elle put. La bouteille tomba dans les vagues et s’en alla en flottant.',
      'Pendant des semaines, Sofia pensa à sa bouteille. Où était-elle ? Flottait-elle toujours ? Une personne gentille l’avait-elle trouvée ? Elle regardait l’horizon chaque après-midi, mais aucune réponse n’arrivait.',
      'Une année passa. Sofia eut dix ans. Elle commençait presque à oublier la bouteille, quand un après-midi, le facteur apporta une lettre à sa porte. L’enveloppe était épaisse et chaude, avec des timbres colorés et étranges, et des bords un peu froissés.',
      'Sofia l’ouvrit. À l’intérieur, il y avait une lettre, écrite avec une écriture soignée et un peu maladroite, dans une langue qu’elle ne connaissait pas. Mais à l’intérieur était glissée une traduction, écrite proprement au crayon.',
      '« Chère Sofia, disait la lettre. Je m’appelle Akemi. J’habite sur une petite île qui s’appelle Hatsushima, très loin de ton pays. Mon grand-père a trouvé ta bouteille sur notre plage. Nous étions étonnés qu’elle ait voyagé si loin. J’ai huit ans. J’ai aussi une chatte, mais la mienne est noire, et elle s’appelle Mochi. J’adore aussi les histoires.',
      '« Mon histoire préférée parle d’un pêcheur qui se lie d’amitié avec une tortue. S’il te plaît, raconte-moi une de tes histoires.',
      '« Avec mon amitié d’au-delà de la mer,',
      'Akemi. »',
      'Sofia lut la lettre trois fois. Ses mains tremblaient, mais elle souriait si fort que ses joues lui faisaient mal.',
      'Cette nuit-là, elle s’assit avec une feuille de papier toute neuve. Elle avait une histoire à raconter, et une nouvelle amie à qui la raconter. Dehors, par sa fenêtre, les vagues continuaient à bouger, doucement et patiemment, comme elles le faisaient depuis mille ans.',
    ],
    comprehension: [
      {
        q: 'Quel cadeau Sofia a-t-elle reçu pour ses neuf ans ?',
        options: [
          'Un livre sur la mer',
          'Une petite bouteille en verre vide',
          'Un nouveau chat',
        ],
        correctIndex: 1,
      },
      {
        q: 'Qui a finalement répondu au message de Sofia ?',
        options: [
          'Un marin qui s’appelle Mochi',
          'Une fille qui s’appelle Akemi, d’une île lointaine',
          'Son oncle, pour rire',
        ],
        correctIndex: 1,
      },
    ],
  },
];

export const frStories: Story[] = raw.map((s) => ({
  ...s,
  language: 'fr',
  wordCount: countWords(s.paragraphs),
  source: 'bundled',
}));
